### ISSUE TITLE
Suggestion...build for multiple platforms and push w/ one command

### ISSUE THREAD

**Issue by aaronhmiller** [svenwal/kong-cicd-tools#3]
Hi Sven! Since I got an M1 for the new job, I've become aware of building for multiple platforms and with that, building and pushing in a single step that I thought you'd appreciate.

`docker buildx build --no-cache --platform linux/amd64,linux/arm64 -t <docker-hub-repo>/<image-name>:$tag --push .`

reference for buildx: https://docs.docker.com/desktop/multi-arch/
and info about --push flag: https://docs.docker.com/engine/reference/commandline/buildx_build/#push

**Comment by svenwal** [comment]
The challenge is not all tools are available as ARM...

**Comment by aaronhmiller** [comment]
Good point. Well, the ability to build and push in one command is nice no?

**Comment by svenwal** [comment]
Absolutely - will use this in other Docker images

**Comment by svenwal** [comment]
With the exception of k6 I have been able to get all tools available cross-plattform so latest version runs on AMD64 as well as ARM64
